version: '3'
services:
  review-service:
    build: ./
    ports:
      - "80:80"
    environment:
      - WAIT_HOSTS=postgres:5432
      - DATABASE_HOST=postgres
      - CONFIG_HOST=##
      - EUREKA_HOST=##
    depends_on:
      - postgres
    links:
      - postgres
  postgres:
    image: postgres:9.4
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=root"
      - "POSTGRES_DB=postgres"
    ports:
      - "5432:5432"
    expose:
      - 5432
